version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - "8084:80"
    volumes:
      - ./docs:/usr/share/nginx/html:ro
    networks:
      - nginx_network

networks:
  nginx_network:
    driver: bridge
