name: "publicacion web"
run-name: "publicacion web"
on: [push] 
permissions:
  contents: write
  actions: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "Instalar dependencias"
        run: |
          npm install
      - name: "Construir proyecto"
        run: |
          npm run build
      - name: "Corregir nombres de carpetas y referencias (_astro -> astro)"
        run: |
          # 1. Renombrar físicamente la carpeta _astro a astro (si existe)
          if [ -d "docs/_astro" ]; then
            mv docs/_astro docs/astro
          fi

          # 2. Reemplazar /_astro/ por /astro/ SOLO en los archivos .html
          find docs -type f -name "*.html" -exec sed -i 's/\/_astro\//\/astro\//g' {} +
      - name: "Guardar cambios en docs"
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs 